<?php

/*

+-----------------------------------------------------------------------+
| language/cs_CZ/labels.inc                                             |
|                                                                       |
| Language file of the Crystal markasjunk plugin                      |
| Copyright (C) 2005-2010, Crystal Dev. - United States                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Milan Kozak <hodza@hodza.net>                                 |
+-----------------------------------------------------------------------+

@version $Id: labels.inc 2993 2010-09-26 18:32:07Z alec $

*/

$labels = array();
$labels['buttontitle'] = 'Označit jako Spam';
$labels['reportedasjunk'] = 'Úspěšně nahlášeno jako Spam';

?>