<?php

$labels = array();
$labels['pwreminder'] = 'Passwort-Erinnerung';
$labels['pwtoolsenabled'] = 'Aktiviert';
$labels['pwtoolsaddress'] = 'Sende Passwort an';
$labels['pwtoolsquestion'] = 'Frage';
$labels['pwtoolsanswer'] = 'Antwort';
$labels['pwtoolsanswerconfirm'] = 'Antwort bestätigen';
$labels['pwtoolsaddidentity'] = 'Bitte fügen Sie eine Identität hinzu';
$labels['pwtoolsadd'] = 'hinzufügen';
$labels['pwtoolsresetpw'] = 'Abschicken';
$labels['pwtoolsexit'] = 'Abbrechen';

$messages = array();
$messages['pwtoolsquestionempty'] = 'Bitte geben Sie eine Frage ein';
$messages['pwtoolsuserempty'] = 'Bitte geben Sie Ihren Benutzernamen ein';
$messages['pwtoolsanswerempty'] = 'Bitte geben Sie Ihre Anwort ein';
$messages['pwtoolsanswernotmatch'] = 'Die Antwort stimmt nicht überein';
$messages['pwtoolsactive'] = 'Passwort-Erinnerung wird eingeschaltet';
$messages['pwtoolsinactive'] = 'Passwort-Erinnerung ist ausgeschaltet';
$messages['pwtoolsusernotfound'] ='Benutzer konnte nicht gefunden werden';
$messages['pwtoolsimcomplete'] ='Die Einstellungen sind unvollständig. Bitte setzen Sie sich mit dem Administrator in Verbindung';
$messages['pwtoolsfailed'] = 'Die Antwort ist falsch.';
$messages['pwtoolssendingfailed'] = 'Die Nachricht konnte nicht versendet werden.';
$messages['pwtoolscheckaccount'] = 'Das Passwort wurde an %s versendet.';

?>
