<?php

$labels = array();
$labels['pwreminder'] = 'Password Reminder';
$labels['pwtoolsenabled'] = 'Reminder enabled';
$labels['pwtoolsaddress'] = 'Send Password to';
$labels['pwtoolsquestion'] = 'Secret Question';
$labels['pwtoolsanswer'] = 'Secret Answer';
$labels['pwtoolsanswerconfirm'] = 'Confirm Secret Answer';
$labels['pwtoolsaddidentity'] = 'Please add an identity';
$labels['pwtoolsadd'] = 'add';
$labels['pwtoolsresetpw'] = 'Submit';
$labels['pwtoolsexit'] = 'Abort';

$messages = array();
$messages['pwtoolsquestionempty'] = 'Please enter your Secret Question';
$messages['pwtoolsuserempty'] = 'Please enter your Username';
$messages['pwtoolsanswerempty'] = 'Please enter your Secret Answer';
$messages['pwtoolsanswernotmatch'] = 'Secret Answer does not match';
$messages['pwtoolsactive'] = 'Password Reminder will be enabled';
$messages['pwtoolsinactive'] = 'Password Reminder is disabled';
$messages['pwtoolsusernotfound'] ='User not found';
$messages['pwtoolsimcomplete'] ='Your Reminder Settings are incomplete. Please contact the Administrator';
$messages['pwtoolsfailed'] = 'Secret Answer is incorrect.';
$messages['pwtoolssendingfailed'] = 'There was an error while sending the message.';
$messages['pwtoolscheckaccount'] = 'Your Password has been sent to %s.';

?>
