<?php

$labels['rss_plugin_name'] = "RSS Feeds";
$labels['rss_all'] = "Alle";
$labels['rss_seen'] = "Gelesen";
$labels['rss_unseen'] = "Ungelesen";
$labels['rss_flagged'] = "Markiert";
$labels['rss_unflagged'] = "Unmarkiert";
$labels['authentication_required'] = "Sie sind nicht angemeldet";
$labels['novalue'] = " ";
$labels['truncated'] = "abgeschnitten";
$labels['mboxempty'] = "Postfach ist leer";

?>