<?php
/*****************************************************************
* Translation by Rodrigo Medeiros Cruz (rodrigo@rmcbrothers.com.br)
* Rmc Brothers - http://www.rmcbrothers.com.br
******************************************************************/
$labels['rss_plugin_name'] = "RSS Feeds";
$labels['rss_all'] = "Todos";
$labels['rss_seen'] = "Vistos";
$labels['rss_unseen'] = "Não Vistos";
$labels['rss_flagged'] = "Sinalizados";
$labels['rss_unflagged'] = "Não Sinalizados";
$labels['authentication_required'] = "Autenticação Requerida";
$labels['novalue'] = " ";
$labels['truncated'] = "truncado";

?>